### Teste Inserir User
POST http://localhost:8800/api/auth/register
Content-Type: application/json

{
    "nome": "John Doe",
    "email": "john.doe@example.com",
    "telefone": "1234567890",
    "senha": "password123",
    "genero": "female",
}

### Teste Buscar Todos os Usuários
GET http://localhost:8800/api/user/users


### Teste Deletar Usuário por Email
DELETE http://localhost:8800/api/user/deleteUser/diogo.oli@gmail.com